*** Variables ***

${DELETE_CONFIRMATION_SCREEN}    ${EMPTY}
${EDIT_PAYMENT_SCREEN}    ${EMPTY}
${comment_TEXT}    ${EMPTY}
${send_money_icon_cug}    ${EMPTY}
${CALENDER_SCREEN}    ${EMPTY}
${remove_favourite_success_screen_tittle_xpath_cug}    ${EMPTY}
${select_payee_edit_schedule_payment}    ${EMPTY}
${search_payee_name}    ${EMPTY}
${invalid_exceeded_amount}    ${EMPTY}
${edit_schedule_payment_select_scheduled_payment_xpath}    ${EMPTY}
${your_payees_add_new_payee_cug}    ${EMPTY}
${SELECT_PAYEE_BANK_SCREEN}    ${EMPTY}
${search_payee_search_payee}    ${EMPTY}
${ALERT_I_UNDERSTAND_SCREEN}    ${EMPTY}
${mismatch_account_munber_error_id}    ${EMPTY}
${calender_ok_button_xpath}    ${EMPTY}
${payment_successfull_msg_cug}    ${EMPTY}
${payment_successfull_comment_cug}    ${EMPTY}
${grid_confirmation_confirm_button_xpath}    ${EMPTY}
${select_payee_bank_hdfc_bank_icon_xpath_cug}    ${EMPTY}
${remove_favourites_confirmation_remove_button_xpath_cug}    ${EMPTY}
${PAYEE_SUCCESSFULLY_DELETED_SCREEN}    ${EMPTY}
${four_digit}    ${EMPTY}
${add_favorite_star_icon}    ${EMPTY}
${PAYEE_SUCESSFULLY_ADDED_FAVOURITES_SCREEN_XPATH}    ${EMPTY}
${grid_pin}    ${EMPTY}
${DELETE_SCHEDULED_PAYMENT}    ${EMPTY}
${pay_now_dropdown}    ${EMPTY}
${VERIFY_OTP_SCREEN}    ${EMPTY}
${RECURRING_PAYMENT_SUCESSFULLY_SCHEDULED}    ${EMPTY}
${verified_tick_id}    ${EMPTY}
${coffee}    ${EMPTY}
${FAVOURITES_ADDED_SUCCESSFULLY}    ${EMPTY}
${neft}    ${EMPTY}
${edit_schedule_payment_payment_date_input_id}    ${EMPTY}
${amount_id_cug}    ${EMPTY}
${payee_option_id}    ${EMPTY}
${manage_button_xpath}    ${EMPTY}
${SEEK_BAR}    ${EMPTY}
${close_button_xpath}    ${EMPTY}
${add_comment}    ${EMPTY}
${rtgs_amount}    ${EMPTY}
${repayment_button_xpath_id}    ${EMPTY}
${enter_amount}    ${EMPTY}
${select_rtgs_payee_delete_schedule_payment}    ${EMPTY}
${minimum_5_digit_error_id}    ${EMPTY}
${schedule_new_payment_button_xpath}    ${EMPTY}
${payee_option_popup_cug}    ${EMPTY}
${add_favourite_payee_screen_title_xpath_cug}    ${EMPTY}
${add_favourite_payee_xpath}    ${EMPTY}
${select_payee_search_icon_on_select_payee}    ${EMPTY}
${view_balance}    ${EMPTY}
${retype_payee_account_number}    ${EMPTY}
${make_recurring_checkbox_xpath}    ${EMPTY}
${payment_successfull_share_cug}    ${EMPTY}
${send_money_manage_icon_xpath_cug}    ${EMPTY}
${add_new_payee_authenticate_with_otp_xpath_cug}    ${EMPTY}
${scheduled_payments_details_edit_button_xpath}    ${EMPTY}
${bills}    ${EMPTY}
${select_date_xpath}    ${EMPTY}
${SCHEDULE_NEW_PAYMENT_SCREEN}    ${EMPTY}
${edit_icon_xpath}    ${EMPTY}
${PAYMENT_SUCCESFUL_SCREEN}    ${EMPTY}
${edit_schedule_payment_cancel_button_xpath}    ${EMPTY}
${SCHEDULED_PAYMENTS_SCREEN}    ${EMPTY}
${delete_scheduled_payments_cancel_button_xpath}    ${EMPTY}
${app_back_button_xpath_cug}    ${EMPTY}
${add_new_payee_add_payee_account_number_payee_name}    ${EMPTY}
${edit_schedule_payment_amount_input_xpath}    ${EMPTY}
${device_back_button}    ${EMPTY}
${remove_favourites_success_green_tick_xpath_cug}    ${EMPTY}
${payment_frequency_monthly_xpath}    ${EMPTY}
${neft_amount}    ${EMPTY}
${my_saving_account}    ${EMPTY}
${error_amount_validation_cug}    ${EMPTY}
${SELECT_PAYEE_SCREEN}    ${EMPTY}
${add_new_payee_isafe_skip_button_id_cug}    ${EMPTY}
${remove_favourites_confirmation_cancel_xpath_cug}    ${EMPTY}
${payment_success_payee_name}    ${EMPTY}
${date}    ${EMPTY}
${tv_from_name_cug}    ${EMPTY}
${select_neft_payee_delete_schedule_payment}    ${EMPTY}
${ADD_FAVORITES_SCREEN}    ${EMPTY}
${balance_validation_cug}    ${EMPTY}
${ADD_NEW_PAYEE_SCREEN}    ${EMPTY}
${no_of_payments_input_xpath}    ${EMPTY}
${Isafe_xpath_cug}    ${EMPTY}
${tv_pay_type_label_cug}    ${EMPTY}
${backspace}    ${EMPTY}
${your_payeee_payee_option_popup_cug}    ${EMPTY}
${select_icici_payee_delete_schedule_payment}    ${EMPTY}
${schedule_pay_button_xpath}    ${EMPTY}
${grid_confirmation_first_input_field_xpath}    ${EMPTY}
${keycode_enter}    ${EMPTY}
${CONFIRM_DETAIL_SCREEN}    ${EMPTY}
${GRID_CONFIRMATION}    ${EMPTY}
${scheduled_payments_details_delete_button_xpath}    ${EMPTY}
${ONE_TIME_PAYMENT_SUCCESSFULLY_SCHEDULED}    ${EMPTY}
${payment_successfull_trans_id_cug}    ${EMPTY}
${payment_successfull_sender_account_no_cug}    ${EMPTY}
${SCHEDULED_PAYMENTS_DETAILS}    ${EMPTY}
${MANAGE_FAVOURITES_SCREEN}    ${EMPTY}
${no_payee_found_xpath}    ${EMPTY}
${add_icici_bank_payee_nick_name}    ${EMPTY}
${delete_payee_confirmation_yes_button_xpath_cug}    ${EMPTY}
${payee_successfully_added_back_to_payments_button_xpath_cug}    ${EMPTY}
${remove_favourite_button_xpath}    ${EMPTY}
${enter_amount_id_cug}    ${EMPTY}
${imps}    ${EMPTY}
${delete_scheduled_payments_delete_button_xpath}    ${EMPTY}
${no_of_payment}    ${EMPTY}
${amount}    ${EMPTY}
${invalid_amount}    ${EMPTY}
${YOUR_PAYEE_SCREEN}    ${EMPTY}
${payee_account_number}    ${EMPTY}
${add_new_payee_add_payee_name}    ${EMPTY}
${delete_payee_confirmation_cancel_button_id_cug}    ${EMPTY}
${search_add_payee}    ${EMPTY}
${alert_new_payee_understand_button_xpath_cug}    ${EMPTY}
${payment_successfull_amount_cug}    ${EMPTY}
${RECENT_TRANSACTION_SCREEN}    ${EMPTY}
${login_pin_id}    Enter 4 Digit
${payment_successfull_copy_cug}    ${EMPTY}
${payment_successfull_mark_fav_cug}    ${EMPTY}
${payment_successfull_payment_option_cug}    ${EMPTY}
${scheduled_payments_button_xpath}    ${EMPTY}
${REMOVE_FAVOURITES_SUCESSFULLY_SCREEN}    ${EMPTY}
${FUND_TRANSFER_SCREEN}    ${EMPTY}
${payment_successfull_account_type_cug}    ${EMPTY}
${add_icici_bank_payee_name}    ${EMPTY}
${mismatch_digit}    ${EMPTY}
${confirm_id}    ${EMPTY}
${select_payee_bank_icici_bank_icon_xpath_cug}    ${EMPTY}
${payment_successfull_payee_name_cug}    ${EMPTY}
${payment_successfull_paid_at_cug}    ${EMPTY}
${login_pin}    ${EMPTY}
${date_edit}    ${EMPTY}
${SCHEDULE_PAYMENT_SUCCESSFULLY_DELETED}    ${EMPTY}
${SCHEDULE_PAYMENT_SUCCESSFULLY_MODIFIED}    ${EMPTY}
${your_payees_delete_payee_button_xpath_cug}    ${EMPTY}
${tv_bank_name_cug}    ${EMPTY}
${payee_successfully_deleted_back_to_transfer_button_xpath_cug}    ${EMPTY}
${payment_successfull_sender_name_cug}    ${EMPTY}
${payment_frequency_dropdown_xpath}    ${EMPTY}
${search_payee_result_click_cug}    ${EMPTY}
${PAYEE_ADDED_SUCESSFULLY_SCREEN}    ${EMPTY}
${recent_transaction_text_xpath}    ${EMPTY}
${add_favourite_xpath}    ${EMPTY}
